# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pathagar
email: pathagar@archive.org
description: > # this means to ignore newlines until "baseurl:"
  Pathagar, the offline digital learning library.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pathagar.info" # the base hostname & protocol for your site
twitter_username: olpcsf
github_username:  pathagarbooks

# Build settings
markdown: kramdown
permalink: pretty

google_analytics: UA-114063224-1

plugins:
  - jekyll-seo-tag
